parameters:
    upload_directory: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Utils\FileHelper:
        arguments:
            $uploadDir: '%upload_directory%'
    admin.student:
        class: App\Admin\StudentAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Student, manager_type: orm, label: Student }
    admin.user:
        class: App\Admin\UserAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\User, manager_type: orm, label: User, show_in_dashboard: false }
    admin.subject:
        class: App\Admin\SubjectAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Subject, manager_type: orm, label: Subject }
